### ISSUE TITLE
Importing pybit results in TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by YoungPilotBe** [bybit-exchange/pybit#116]
from pybit.unified_trading import *
import config

session = HTTP(
    testnet=False,
    api_key=config.api_key,
    api_secret=config.api_secret,
)

Throws this error

'type' object is not subscriptable
TypeError: 'type' object is not subscriptable

**Comment by dextertd** [comment]
Can you describe the environment in which you installed pybit? I just pip installed it and I cannot reproduce the issue in the python interpreter

```
uk09002ml@UK09002ML ~ % 
uk09002ml@UK09002ML ~ % python3
Python 3.9.5 (default, May  4 2021, 03:36:27) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybit.unified_trading import *
>>> session = HTTP(
...     testnet=False,
...     api_key="...",
...     api_secret="...",
... )
>>> import pybit
>>> print(pybit.VERSION)
5.0.0
```

**Comment by RayXie29** [comment]
Same error, pybit version 5.1.1
Solve the error by 
`retry_codes: defaultdict[dict] = field(
        default_factory=lambda: {},
        init=False,
  )`
to
`retry_codes: defaultdict(dict) = field(
        default_factory=lambda: {},
        init=False,
   )`
Full error message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-6613d271d74d> in <module>
----> 1 from pybit.unified_trading import WebSocket

~/anaconda3/envs/mlenv/lib/python3.8/site-packages/pybit/unified_trading.py in <module>
      5     UnauthorizedExceptionError,
      6 )
----> 7 from ._v5_market import MarketHTTP
      8 from ._v5_trade import TradeHTTP
      9 from ._v5_account import AccountHTTP

~/anaconda3/envs/mlenv/lib/python3.8/site-packages/pybit/_v5_market.py in <module>
----> 1 from ._http_manager import _V5HTTPManager
      2 from .market import Market
      3 
      4 
      5 class MarketHTTP(_V5HTTPManager):

~/anaconda3/envs/mlenv/lib/python3.8/site-packages/pybit/_http_manager.py in <module>
     27 
     28 @dataclass
---> 29 class _V5HTTPManager:
     30     testnet: bool = field(default=False)
     31     domain: str = field(default="bybit")

~/anaconda3/envs/mlenv/lib/python3.8/site-packages/pybit/_http_manager.py in _V5HTTPManager()
     37     recv_window: bool = field(default=5000)
     38     force_retry: bool = field(default=False)
---> 39     retry_codes: defaultdict[dict] = field(
     40         default_factory=lambda: {},
     41         init=False,

TypeError: 'type' object is not subscriptable

**Comment by dextertd** [comment]
Thank you, it looks like this happens on python3.8. It works on python3.9. Please upgrade your python version. I will fix the pybit requirements.

**Comment by dextertd** [comment]
I cannot reproduce the problem. I tested on python3.7 and python3.8 and used both variations (`defaultdict[dict]`, `defaultdict(dict)`) but I never got this error.

**Comment by vaalici** [comment]
I had the same issue, with `retry_codes: defaultdict(dict)` instead of `retry_codes: defaultdict[dict]` solved my problem.

**Comment by RayXie29** [comment]
Is this cause by differences between python version? Mine is 3.8.5 btw,

**Comment by dextertd** [comment]
Hey @ervuks, any idea about this? I'm stumped. I can't seem to reproduce the problem although have seen it reported several times now.

**Comment by sheungon** [comment]
Same issue with python 3.8.16.
I can fix the issue by changing the following in "pybit/_http_manager.py"
```
retry_codes: defaultdict[dict] = field(
    default_factory=lambda: {},
    init=False,
)
ignore_codes: dict = field(
    default_factory=lambda: {},
    init=False,
)
```
To
```
retry_codes: set = field(
    default_factory=lambda: {},
    init=False,
)
ignore_codes: set = field(
    default_factory=lambda: {},
    init=False,
)
```

**Comment by ervuks** [comment]
The issue might be caused using not supported Python version. 
From readme: `pybit requires Python 3.9.1 or higher. `
https://github.com/bybit-exchange/pybit/blob/master/README.md#installation 

The problem occurs with dataclass usage and initialisation.

**Comment by sheungon** [comment]
> The issue might be caused using not supported Python version. From readme: `pybit requires Python 3.9.1 or higher. ` https://github.com/bybit-exchange/pybit/blob/master/README.md#installation
> 
> The problem occurs with dataclass usage and initialisation.

yes, very likely it is.
I didn't read thought the README and misunderstood the top part python "3.6", "3.7", "3.8", "3.9", "3.10" at
https://github.com/bybit-exchange/pybit/blob/master/README.md#pybit

Thought it worked with 3.8 ;D

**Comment by dextertd** [comment]
Okay, I'll change the top part so that it's only >=3.9, this seems like the most reliable solution, as no one has reported the issue on 3.9

**Comment by NameArtem** [comment]
> Same issue with python 3.8.16. I can fix the issue by changing the following in "pybit/_http_manager.py"
> 
> ```
> retry_codes: defaultdict[dict] = field(
>     default_factory=lambda: {},
>     init=False,
> )
> ignore_codes: dict = field(
>     default_factory=lambda: {},
>     init=False,
> )
> ```
> 
> To
> 
> ```
> retry_codes: set = field(
>     default_factory=lambda: {},
>     init=False,
> )
> ignore_codes: set = field(
>     default_factory=lambda: {},
>     init=False,
> )
> ```

This works for me.
