### ISSUE TITLE
withdraw address is invalid

### ISSUE THREAD

**Issue by nZF5fb9gVP** [bybit-exchange/pybit#122]
```python
from time import time
from pybit import _v5_asset

_session = _v5_asset.AssetHTTP(api_key="_", api_secret="_")

def withdraw_trx_to_address(wallet:str, amount:float) -> bool:
    return _session.withdraw(
        coin="TRX",
        chain="TRC20",
        address=wallet,
        amount=str(amount),
        timestamp=int(time() * 1000),
    )
withdraw_trx_to_address("TW8pEPPHj6MXTAnxDhbDmM5v76qmicBPwi", 15)
```
error: "pybit.exceptions.InvalidRequestError: withdraw address is invalid (ErrCode: 131002) (ErrTime: 01:38:12).
Request → POST https://api.bybit.com/v5/asset/withdraw/create: {"coin": "TRX", "chain": "TRC20", "address": "TW8pEPPHj6MXTAnxDhbDmM5v76qmicBPwi", "amount": "15", "timestamp": 1681004292332}."
How can I fix the error ?

**Comment by Kamsby** [comment]
Chain should be TRX. Use this endpoint to check the chain values ( /v5/asset/coin/query-info?coin=TRX )

 "chain": "TRX"
