### ISSUE TITLE
WebSocket automatically reconnects but does not resubscribe to topics

### ISSUE THREAD

**Issue by windhamwong** [bybit-exchange/pybit#13]
Likely my previous PR is not working. The disconnecting issue is still there happening silently. Might need to deep dive into the code and check what is wrong there
#8

**Comment by dextertd** [comment]
#14 adds extra debug logging, which I have been meaning to do for a while, and you should be able to upgrade to release candidate version 2.1.1rc0 and pass `trace_logging=True` when creating the ws object. Hope that can help you check pings/pongs and any other relevant info for checking if the connection is still alive

**Comment by windhamwong** [comment]
@dextertd I believe the PR was good and the WebSocket is reconnecting successfully. However, as there is no special handle with this reconnection, the subscription actions cannot be redone after reconnected making the reconnection useless.
I believe adding a `reconnect_callback=callback` could solve the issue, however, this could be changing the project coding style and structure. I need your comment about this. I can make a PR if this has no issue at all.

**Comment by windhamwong** [comment]
I suspect that, 
https://github.com/bybit-exchange/pybit/blob/d0e794697121564966f0d9b9253508ea30c110b4/pybit/_websocket_stream.py#L152
does work for reconnecting, however, the subscription cannot be recovered, raising error from
https://github.com/bybit-exchange/pybit/blob/d0e794697121564966f0d9b9253508ea30c110b4/pybit/_websocket_stream.py#L365
if I use my own modified version, to do a callback override when 
https://github.com/bybit-exchange/pybit/blob/d0e794697121564966f0d9b9253508ea30c110b4/pybit/_websocket_stream.py#L140
is triggered for re-subscribing all my topics.

I am suggesting to add
`self.callback_directory = {}` to
https://github.com/bybit-exchange/pybit/blob/d0e794697121564966f0d9b9253508ea30c110b4/pybit/_websocket_stream.py#L160

**Comment by dextertd** [comment]
Yes of course, not sure how I overlooked that. So websocket reconnection is okay, just subscriptions are not sent again on the new connection...

I agree with modifying the `_reset` method in the way you suggest although I think pybit should handle resubscription for the user as well. Will have a think of the best way to do that

**Comment by windhamwong** [comment]
I will do a PR for this. See if the PR matches the flow you want to have.

**Comment by windhamwong** [comment]
I do have a solution of this, but it relies on external callback to call `__init__()` again to retrigger everything. I personally don't see this as a solution to solve the issue, thus I am not going to make a PR for this.
However, there is a hint that, the `self.callback_directory` should be reset during the `super(__init__)` with `self.callback_directory = {}`, otherwise the callback might remain disconnected. However, this might bring up another issue of re-subscribing topics, it requires a special handle in this case.

**Comment by windhamwong** [comment]
@dextertd If you do have suggestion in this, we can work together to make a working PR solution.

**Comment by dextertd** [comment]
@windhamwong Without having actually tried this in code, I think the best way would be to create a variable in `_WebSocketManager`, something like
```
self.subscriptions = []
```
and every time a subscription message is sent, store the data in there. It's probably best to store the entire JSON sent because then you can easily fit around the spot websocket's arguments.

So the challenge is to make it work for not only futures, but spot too. Futures is easy, the `args` JSON key is just a list of strings (so just store that list), but in spot there are extra arguments that need to be stored too. Unsure the best way to do that (store in dumped string JSON or python dict - which ever's easiest).

Then, possibly in `_on_error`, after `self._connect(self.endpoint)` is called, it should resub to the topics.

---

At the minute I'm working on adding USDC options to pybit but after that would be happy to assist & test if needed

**Comment by dextertd** [comment]
Oh and USDC perps & options both pretty much follow the futures (inverse, linear (USDT)) format, so that shouldn't throw a spanner into the works.

**Comment by windhamwong** [comment]
> @windhamwong Without having actually tried this in code, I think the best way would be to create a variable in `_WebSocketManager`, something like
> 
> ```
> self.subscriptions = []
> ```
> 
> and every time a subscription message is sent, store the data in there. It's probably best to store the entire JSON sent because then you can easily fit around the spot websocket's arguments.
> 
> So the challenge is to make it work for not only futures, but spot too. Futures is easy, the `args` JSON key is just a list of strings (so just store that list), but in spot there are extra arguments that need to be stored too. Unsure the best way to do that (store in dumped string JSON or python dict - which ever's easiest).
> 
> Then, possibly in `_on_error`, after `self._connect(self.endpoint)` is called, it should resub to the topics.
> 
> At the minute I'm working on adding USDC options to pybit but after that would be happy to assist & test if needed

You are right, this line of code is necessary for reconnection. However, I am still seeing multiple disconnection at the same time, and I can't verify whether it is correctly reconnected or not.

So far my temp solution is callback an external function outside of library, and recreate a new handle for it. I make sure the previous handle is destroyed by modifying the library code. This is why I don't see this a good solution to PR as it requires additional external functions.

I can confirm that the `self.subscriptions = []` is one of the necessary during the reconnection. But I can't confirm if there is other cleanup is required.

**Comment by dextertd** [comment]
#38 should fix this. Please try it @windhamwong 

```
pip install pybit==2.2.2rc2
```

**Comment by windhamwong** [comment]
Was revisiting this issue recently. I will have a try on it.

**Comment by ImaRicklePick** [comment]
Tested on docker, python 3.9, pybit==2.2.2rc2

### [Inverse perpetual btc/usd public instrument_info_stream log](https://pastebin.com/s4gXpKYe)
```
ws_inverse = inverse_perpetual.WebSocket(
    test=True,
    domain="bytick",  # the default is "bybit"
    trace_logging=True,
    ping_interval=60
)
```
Disconnect is @ timestamp 2022-06-16 13:11:37,593
Disabled wifi for a minute and WebSocket reconnected within default ping_timeout window after that. Don't see any problems for now.

**Comment by ImaRicklePick** [comment]
Pasting some key points from telegram discussion:

My messages:
> Well, after interval and timeout, pybit throws this error:

> ERROR error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x7f40e7ca5e50>: Connection failed.

> I think we’re safe to say that devs should know how to properly calculate their needed ping_interval and ping_timeout values and after these counts are finished, developer should deal with raised error on his/her side. Though, if ping_interval is a huge huge number, wss should work without stops for ever 😄

[pybit while cycle with X retries and error that needs to be changed](https://github.com/bybit-exchange/pybit/blob/master/pybit/_websocket_stream.py#L126)

Dexter:
> I don't think this is how websocket-client works. When there's an error, on_error is called. In my testing this usually happens because the ping timeout is reached. Other exceptions could be raised, of course, but this is the main one.

> "Though, if ping_interval is a huge huge number, wss should work without stops for ever" - If you aren't sending pings frequently, the websocket might not realise it's disconnected and so you are under the impression it's still open, pybit doesn't try to reconnect, but you're receiving no messages. This does not seem like a reliable way to use the websocket.

Problem that we found:

pybit wss sends ping/pong requests at every ping_interval seconds. If there is no/bad response from bybit after ping_timeout seconds, pybit tries to reconnect (the url points to the while script which tries reconnecting) for 10 times and raises an error if connection is failed. Users expect pybit to keep the connection until the user interrupts it. So, if network is down for longer than a total of (ping_timeout + ping_interval + 10 retries to reconnect) - pybit just stops.

Possible solutions:

remove retries variable and rely solely on ping_interval and ping_timeout values or as I wrote:

> Orrrrr you can add something like force_reconnection, reconnect_on_error booleans and max_retries int. So if user wants to force a reconnection after failed one, we can repeat it for max_retries times and then if reconnect_on_error is set to True, we don’t throw an error but just reset the whooooole mechanism, if it is set to False, throw an error that exists now. Thus, all the scenarios can be acomplished by both sides - dev and lib
> And if people don’t want to deal with error handling, wss would just keep on repeating connection until it succeeds?
> That’s a small tweak but gives some space for customisation.

I would like to see the latter solution being implemented. If any of you have any other proposals, let's discuss and code them.

**Comment by dextertd** [comment]
Added a `retries` argument #40. Set it to `0` and the WSS will try to reconnect forever. I think this is the simplest solution and basically addresses your concerns @ImaRicklePick

**Comment by dextertd** [comment]
@windhamwong Wondering if you ever tried it out? I'll close this issue if you have no further concerns...

```
pip install pybit==2.2.3
```

**Comment by windhamwong** [comment]
was sick for last 2 weeks, gonna test out this weekend, sorry

**Comment by dextertd** [comment]
Sorry to hear that. No rush, just test it when you have time and I'll feel confident to close this issue

**Comment by GranpaRick** [comment]
> Added a `retries` argument #40. Set it to `0` and the WSS will try to reconnect forever. I think this is the simplest solution and basically addresses your concerns @ImaRicklePick

Will give it a try this weekend.

**Comment by windhamwong** [comment]
It takes some time for me to test out the timeout as it does not often happen every day.

**Comment by windhamwong** [comment]
I can confirm the patch can reconnect without issue. I am testing on re-subscribe of topics now

**Comment by windhamwong** [comment]
I can confirm the reconnection works without issue now. Thanks for the great work!

**Comment by aidonchuk** [comment]
> I can confirm the patch can reconnect without issue. I am testing on re-subscribe of topics now

Hi! Did you finish resubscribe? Thx
