### ISSUE TITLE
Need help about margin trading

### ISSUE THREAD

**Issue by fpshuang** [bybit-exchange/pybit#131]
Hi, thx for your wonderful job!

However, I am confused about margin trading with pybit.

1. Do I need borrow coins and then do margin trading?
2. Could your give me a tutorial about do margin trading in UTA?

Looking forward to your reply.
Regards

**Comment by dextertd** [comment]
1. If you are not in UTA then yes you have to make an explicit request to borrow coins. In UTA, it is done automatically.
2. There is no API tutorial, but the documentation for UTA spot margin trading is here: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/switch-mode
