### ISSUE TITLE
Historical Kline data

### ISSUE THREAD

**Issue by einarjohnson** [bybit-exchange/pybit#144]
Hello ByBit folks. I was wondering, is it possible to download historic Kline data (on a csv format or something similar)? I'm doing a research project and I wanted to keep all the historic data in my own database and I was hoping I could avoid spamming the https://bybit-exchange.github.io/docs/v5/market/kline API and the only resource I have found so far is here https://public.bybit.com/ which doesn't seem to have the data I'm looking for.

**Comment by dextertd** [comment]
You can get archived trading history in a CSV https://bybit-exchange.github.io/docs/v5/market/recent-trad

and you can build klines from this data. But there are no CSV klines directly available.

**Comment by einarjohnson** [comment]
> You can get archived trading history in a CSV https://bybit-exchange.github.io/docs/v5/market/recent-trad
> 
> and you can build klines from this data. But there are no CSV klines directly available.

Thanks, i will take a look at this resource

**Comment by dextertd** [comment]
Sorry there is a typo in that link, the correct one is https://bybit-exchange.github.io/docs/v5/market/recent-trade
