### ISSUE TITLE
I can´t stablish connection

### ISSUE THREAD

**Issue by IsaTTeN** [bybit-exchange/pybit#149]
Hello!

My apologies, I know this is pretty basic. I am starting to use this API and I am not even able to stablish a conection

This is the code that I am using

`from pybit import usdt_perpetual
import time
import config

session = usdt_perpetual.HTTP(
    endpoint='https://api.bybit.com',
    api_key='lalalala',
    api_secret='lalalalala',
    testnet = True,
)`

I get this error: 

ImportError: cannot import name 'usdt_perpetual' from 'pybit'

What am I doing wrong?

Thank you and have a fantastic day

**Comment by dextertd** [comment]
If you want to use the `usdt_perpetual` module you need to downgrade to a version below 5.0.0

If you want to use the current version, you can refer to the API documentation to see the latest examples per endpoint https://bybit-exchange.github.io/docs/v5/order/create-order

**Comment by IsaTTeN** [comment]
It worked using unified_trading

Thank you very much
