### ISSUE TITLE
recvWindow exception

### ISSUE THREAD

**Issue by Simongolovinskiy** [bybit-exchange/pybit#159]
I have a problem with auth channels. 2023-08-17 11:32:10 - pybit._http_manager - ERROR - Timestamp for this request is outside of the recvWindow. (ErrCode: 10002). Added 2.5 seconds to recv_window. 2 retries remain. I am receiving it every time i try to get my balance or close orders. What is this exception? Two days ago it worked and all was good

**Comment by Simongolovinskiy** [comment]
If someone have this exception - just synchronize your time in Operation system

**Comment by it-viktor** [comment]
I sometimes encounter this error, why? My application works well, making trades every day, but I've noticed that I get this error during volatility. How should I write the program to prevent its occurrence in the future?
