### ISSUE TITLE
Quickstart websocket example only giving one OB every few seconds

### ISSUE THREAD

**Issue by mvanaltvorst** [bybit-exchange/pybit#160]
https://github.com/bybit-exchange/pybit/blob/master/examples/websocket_example_quickstart.py

This is the example I'm referring to. Whenever I run it, I'm only getting a new line printed on the screen every few seconds. I would expect a new message every 20ms.

Can reproduce both in Europe as well as in Singapore (ap-southeast-1). 

Am I doing something wrong?

**Comment by dextertd** [comment]
That file is using the testnet which may not be very liquid. So, slow updates might be expected, as there simply isn't anything happening for a few seconds. Try setting `testnet=False` and seeing if that changes things.

**Comment by mvanaltvorst** [comment]
Oh of course, thank you!
