### ISSUE TITLE
cannot connect to wss://stream.bybit.com/v5/public/option

### ISSUE THREAD

**Issue by carolinareaperouch** [bybit-exchange/pybit#164]
I used the code snippet from the [docs](https://bybit-exchange.github.io/docs/v5/websocket/public/ticker) for options:
```
from pybit.unified_trading import WebSocket
from time import sleep
ws = WebSocket(
    testnet=True,
    channel_type="option",
)
def handle_message(message):
    print(message)
ws.ticker_stream(
    symbol="tickers.BTC-22JAN23-17500-C",
    callback=handle_message
)
while True:
    sleep(1)
```

I receive no data back and this error over and over:

```WebSocket Unified V5 (wss://stream.bybit.com/v5/public/option) encountered error: Connection to remote host was lost..```

I have also set `testnet = False` and used `symbol="tickers.ETH-27SEP23-1650-P"` but I'm still getting the same error.

I also tried using my own implementation in Python:
```
async def call_api(symbols):
    subscribe_msg = {
        "op": "subscribe",
        "args": [f"tickers.{symbol}" for symbol in symbols]
    }
    custom_ping_msg = json.dumps({
        "op": "ping",
    })

    async with websockets.connect('wss://stream.bybit.com/v5/public/option') as websocket:
        await websocket.send(json.dumps(subscribe_msg))

        async def keep_alive():
            while websocket.open:
                await asyncio.sleep(10)
                # Send custom ping message as a regular text message
                await websocket.send(custom_ping_msg)
        
        # Start the keep_alive task
        keep_alive_task = asyncio.ensure_future(keep_alive())

        try:
            while websocket.open:
                response = await websocket.recv()
                response = json.loads(response)
                
                # Check if the received message is a "Pong" message
                if response.get("op") == "pong":
                    print("Pong received")
                else:
                    print(json.dumps(response, indent=4))
                    # check_alerts(response, data, seen)
        finally:
            keep_alive_task.cancel()
            # If the connection is closed, perform necessary cleanup
            print("Connection closed")
```

 and I am able to receive data for about 30 seconds. However, after 30 seconds, I lose connection to the server and get this error: 

```websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received```

**Comment by dextertd** [comment]
I can reproduce this. Let me investigate.

**Comment by InTheta** [comment]
issue still persists

**Comment by Kamsby** [comment]
yes, we will fix it soon

**Comment by dextertd** [comment]
The websocket client library waits for twice the length of the `ping_interval` passed to it before sending the first ping message, and as a ping is required every 30 seconds but pybit's default is 20 seconds, it takes 20*2=40 seconds to send the first ping – and as no ping was received within 30 seconds the server terminates the connection.

Solved by sending a single initial ping (`_send_initial_ping`) after creating the connection.

**Comment by johnslavik** [comment]
This solution leads to sending pings after calling the `_WebSocketManager.exit()` method:
```
# _WebSocketManager.exit() method was called, but the timer thread (Thread-3) is still alive
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File ".../.venv/lib/python3.10/site-packages/pybit/_websocket_stream.py", line 259, in _send_custom_ping
    self.ws.send(self.custom_ping_message)
  File ".../.venv/lib/python3.10/site-packages/websocket/_app.py", line 291, in send
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```
`_WebSocketManager.exit()` should call `<ping timer>.cancel()` before performing its underlying logic. The timer thread shouldn't exist after the websocket thread dies. Also, on a side note, the handlers have bugs... `IndexError`... #220
