### ISSUE TITLE
404 while calling place batch order

### ISSUE THREAD

**Issue by jeffhappily** [bybit-exchange/pybit#165]
I'm trying to call the `place_batch_order` in Python
```py
session = HTTP(testnet=False, api_key=api_key, api_secret=secret_key)

response = session.place_batch_order(
    category="linear",
    request=[...],
)
```

but I'm getting an error saying
```
An error occurred while placing the order: Http status code is not 200. (ErrCode: 404) (ErrTime: 03:01:53).
Request → POST https://api.bybit.com/v5/order/create-batch
```

**Comment by LaAlquimia** [comment]
I got same on  get_positions()


![image](https://github.com/bybit-exchange/pybit/assets/38500708/5f83c6f5-b4b4-4682-945b-0bcf06bcdf5f)

**Comment by Kamsby** [comment]
@LaAlquimia Make sure you are passing the category.

@jeffhappily place_batch_order is only for UTA PRO users. Did you upgrade your account ?

**Comment by jeffhappily** [comment]
@Kamsby Sorry I was not aware of that. I know there UTA (Unified Trading Account) but what's UTA Pro and how do I get it?

**Comment by Kamsby** [comment]
@jeffhappily Goto https://www.bybit.com/app/user/api-management and click "Upgrade Now" button for UTA PRO

<img width="1267" alt="Screenshot 2023-09-28 at 2 30 32 PM" src="https://github.com/bybit-exchange/pybit/assets/93309482/89c87628-0bad-46ce-8cf7-64a0ee17b2f8">

**Comment by BCusack** [comment]
Needs to be added to documentation - wasted a bit of time today on this one. Better error response than 404 would help.

**Comment by dextertd** [comment]
Docs [say](https://bybit-exchange.github.io/docs/v5/order/batch-place) UTA Pro:
> Covers: Option (UTA, UTA Pro) / USDT Perpetual, UDSC Perpetual, USDC Futures (UTA Pro)

**Comment by LaAlquimia** [comment]
> UTA

Works for me
