### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto' since pybit 5.6.0

### ISSUE THREAD

**Issue by MasterGeorges67** [bybit-exchange/pybit#167]
I tried out today the updated version of pybit (5.6.0) and code is no longer running!

     from pybit.unified_trading import HTTP
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\unified_trading.py", line 7, in <module>
    from ._v5_misc import MiscHTTP
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\_v5_misc.py", line 1, in <module>
    from ._http_manager import _V5HTTPManager
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\_http_manager.py", line 6, in <module>
    from Crypto.Hash import SHA256
ModuleNotFoundError: No module named 'Crypto'

I already added the crypto module (by pip), do not change, still error.
When I revert to 5.5.0, all is working correct.

What did I missing? Is there some news about this?

**Comment by CodiPapi** [comment]
I had to install PyCryptoDome myself using pip (even though it is listed in the requirements.txt)
[https://pycryptodome.readthedocs.io/en/latest/src/installation.html](https://pycryptodome.readthedocs.io/en/latest/src/installation.html)

**Comment by MasterGeorges67** [comment]
It is still not working with version 5.6.0!
I have installed:
- pycryptodome              3.19.0
- pycryptodome-test-vectors 1.0.13
and executed the python3 -m Cryptodome.SelfTest, which was sucessfully.
Still get ModuleNotFoundError: No module named 'Crypto'
Any other ideas?

**Comment by dextertd** [comment]
Sounds like you're not using the packages from the requirements https://github.com/bybit-exchange/pybit/blob/master/requirements.txt

When at the path of pybit, you should do 
```
pip install -r requirements.txt
```

**Comment by MasterGeorges67** [comment]
Sorry to say this again, I did install the required packages:
pycryptodome==3.19.0
websocket-client==1.5.0
requests>=2.22.0
My simple code is running with the older version of pybit 5.5.0, whitout any problem!
After upgrade pybit to the latest build 5.6.0, I get:
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\unified_trading.py", line 7, in <module>
    from ._v5_misc import MiscHTTP
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\_v5_misc.py", line 1, in <module>
    from ._http_manager import _V5HTTPManager
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\_http_manager.py", line 6, in <module>
    from Crypto.Hash import SHA256
ModuleNotFoundError: No module named 'Crypto'
There must be something wrong.
Thanks for you support

**Comment by Tirzono** [comment]
So the issue here is that pycryptodome is missing in the setup.py. That's what pip looks at when installing pybit. @dextertd, do you want me to create a PR for that?

**Comment by sjagadee** [comment]
Still not fixed, still getting this issue.  For 5.7.0

**Comment by rodionstepanov** [comment]
@sjagadee 
> Still not fixed, still getting this issue. For 5.7.0

I had the same problem.
Solution:
```
pip uninstall crypto
pip uninstall pycryptodome
pip install pycryptodome
```

**Comment by tuanteku9x** [comment]
> @sjagadee
> 
> > Still not fixed, still getting this issue. For 5.7.0
> 
> I had the same problem. Solution:
> 
> ```
> pip uninstall crypto
> pip uninstall pycryptodome
> pip install pycryptodome
> ```

Thanks, solved
