### ISSUE TITLE
Can't close position with qty="0"

### ISSUE THREAD

**Issue by Kenisy** [bybit-exchange/pybit#168]
The [document](https://bybit-exchange.github.io/docs/v5/order/create-order) says:

> In particular, for Futures & Perps, if you pass qty="0", you can close the whole position of current symbol

However when I call session.place_order(category="linear", symbol="BTCUSDT", side="Buy", orderType="Market", qty="0") it always return:

> pybit.exceptions.InvalidRequestError: The number of contracts exceeds minimum limit allowed (ErrCode: 10001)

Could you tell me what i did wrong ?

**Comment by Kamsby** [comment]
For closing the position, **_send opposite side order with reduceOnly as True_**
