### ISSUE TITLE
Simple access session HTTP no longer running with pybit version 5.6.0

### ISSUE THREAD

**Issue by MasterGeorges67** [bybit-exchange/pybit#169]
I still have issue with 5.6.0:
`#!/usr/bin/env python
import configparser
from pybit.unified_trading import HTTP

if __name__ == '__main__':
    config = configparser.ConfigParser()
    config.read('config_TB3.ini')

    try:
        session = HTTP(
            testnet=False,
            timeout=int(config['bybit.com']['timeout']),
            api_key=config['bybit.com']['API_KEY'],
            api_secret=config['bybit.com']['API_SECRET'],
        )
    except Exception as e:
        print("Error: connecting to Bybit failed!")
        exit(-1)

    print(session.get_orderbook(category="linear", symbol="BTCUSDT"))
`
(env) PS E:\programming\Project\TradeBot3> python .\simple_example.py
Traceback (most recent call last):
  File "E:\programming\Project\TradeBot3\simple_example.py", line 3, in <module>
    from pybit.unified_trading import HTTP
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\unified_trading.py", line 7, in <module>
    from ._v5_misc import MiscHTTP
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\_v5_misc.py", line 1, in <module>
    from ._http_manager import _V5HTTPManager
  File "E:\programming\Project\TradeBot3\env\Lib\site-packages\pybit\_http_manager.py", line 6, in <module>
    from Crypto.Hash import SHA256
ModuleNotFoundError: No module named 'Crypto'

(env) PS E:\programming\Project\TradeBot3> pip install pybit==5.5.0  
Collecting pybit==5.5.0
  Using cached pybit-5.5.0-py2.py3-none-any.whl
Requirement already satisfied: requests in e:\programming\project\tradebot3\env\lib\site-packages (from pybit==5.5.0) (2.31.0)
Requirement already satisfied: websocket-client in e:\programming\project\tradebot3\env\lib\site-packages (from pybit==5.5.0) (1.5.0)
Requirement already satisfied: websockets in e:\programming\project\tradebot3\env\lib\site-packages (from pybit==5.5.0) (11.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\programming\project\tradebot3\env\lib\site-packages (from requests->pybit==5.5.0) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in e:\programming\project\tradebot3\env\lib\site-packages (from requests->pybit==5.5.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\programming\project\tradebot3\env\lib\site-packages (from requests->pybit==5.5.0) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in e:\programming\project\tradebot3\env\lib\site-packages (from requests->pybit==5.5.0) (2023.7.22)
Installing collected packages: pybit
  Attempting uninstall: pybit
    Found existing installation: pybit 5.6.0
    Uninstalling pybit-5.6.0:
      Successfully uninstalled pybit-5.6.0
Successfully installed pybit-5.5.0
(env) PS E:\programming\Project\TradeBot3> python .\simple_example.py
{'retCode': 0, 'retMsg': 'OK', 'result': {'s': 'BTCUSDT', 'b': [['27673', '26.347'], ['27672.9', '0.119'], ['27672.8', '0.931'], ['27672.7', '0.362'], ['27672.6', '0.108'], ['27672.5', '0.367'], ['27672.4', '0.012'], ['27672.3', '1.002'], ['27672.2', '0.363'], ['27672.1', '1.648'], ['27672', '1.802'], ['27671.9', '1.749'], ['27671.8', '0.001'], ['27671.7', '0.567'], ['27671.6', '2.715'], ['27671.5', '0.003'], ['27671.4', '1.001'], ['27671.3', '0.001'], ['27671.2', '0.001'], ['27671.1', '0.001'], ['27671', '0.181'], ['27670.7', '0.325'], ['27670.4', '0.047'], ['27670.3', '0.008'], ['27670.2', '2.55']], 'a': [['27673.1', '1.986'], ['27673.2', '0.588'], ['27673.3', '1.445'], ['27673.4', '0.361'], ['27673.5', '0.361'], ['27673.6', '0.723'], ['27673.9', '1.03'], ['27674', '0.205'], ['27674.1', '6.278'], ['27674.2', '0.001'], ['27674.3', '0.001'], ['27674.4', '0.001'], ['27674.5', '0.001'], ['27674.6', '0.001'], ['27674.8', '0.072'], ['27675', '1.482'], ['27675.4', '0.701'], ['27675.5', '0.729'], ['27675.6', '0.902'], ['27675.7', '0.163'], ['27675.8', '0.001'], ['27675.9', '0.005'], ['27676', '0.374'], ['27676.1', '0.154'], ['27676.2', '0.011']], 'ts': 1696587013627, 'u': 25095339}, 'retExtInfo': {}, 'time': 1696587013690}
My requirements.txt include all this:
pybit
pycryptodome==3.19.0
websocket-client==1.5.0
requests>=2.22.0
There must be a problem in version pybit 5.6.0
I am not sure, but the the imports:
from Crypto.Hash import SHA256
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
Must they not spelled like this:
from crypto.Hash import SHA256
from crypto.PublicKey import RSA
from crypto.Signature import PKCS1_v1_5
in small letter? I see it in this direction not sure where the problem really is located, but is there!
Thanks for any support

**Comment by MasterGeorges67** [comment]
I found a workaround! (problem only on Windows)
If I rename the folder e:\programming\Project\TradeBot3\env\Lib\site-packages\crypto, to e:\programming\Project\TradeBot3\env\Lib\site-packages\Crypto
My small example is working again!
I am not sure where the root of the problem is, but something is not matching correct.
Best regards,

**Comment by dextertd** [comment]
I can't seem to reproduce this. If you create a fresh virtual environment, are you able to reproduce?
