### ISSUE TITLE
pybit - ERROR - WebSocket Non-Authenticated encountered error: Connection to remote host was lost

### ISSUE THREAD

**Issue by annamatynian** [bybit-exchange/pybit#172]
Hello!

I'm using the code below to create a websocket connection to ByBit:

from pybit import HTTP
from pybit import WebSocket

#configuration variables
mode = 'test'
timeframe = 60
kline_limit = 200
z_score_window = 21

#LIVE API
api_key_mainnet = " "
api_secret_mainnet = " "

#TEST API
api_key_testnet = "XXX"
api_secret_testnet = "YYY"

#SELECTED API
if mode == 'test':
    api_key = api_key_testnet
else:
    api_key = api_key_mainnet
if mode == 'test':
    api_secret = api_secret_testnet
else:
    api_secret = api_secret_mainnet

#SELECTED URL
if mode == "test":
    api_url = "https://api-testnet.bybit.com"
else:
    "https://api.bybit.com"

# SESSION Activation
session = HTTP(api_url)

# Web Socket Connection

subs = [
    "candle.1.BTCUSDT"
]
ws = WebSocket(
    "wss://stream-testnet.bybit.com/v5/public/spot",
    subscriptions=subs
)

while True:
    data = ws.fetch(subs[0])
    if data:
        print(data)
However I'm getting this error when running it: "pybit - ERROR - WebSocket Non-Authenticated encountered error: Connection to remote host was lost.."

Why can this happen?

The pybit version I'm using is 1.3.6 (this is a necessary condition, as the code is a from tutorial created 2 years ago and it doesn't work with later versions of pybit)

Thank you!

**Comment by dextertd** [comment]
Cannot guarantee that 1.3.6 will work with V5 websocket endpoints, as it was built before these were available; sorry.

You can use this example instead (from https://bybit-exchange.github.io/docs/v5/websocket/public/kline)

```
from pybit.unified_trading import WebSocket
from time import sleep
ws = WebSocket(
    testnet=True,
    channel_type="spot",
)
def handle_message(message):
    print(message)
ws.kline_stream(
    interval=1,
    symbol="BTCUSDT",
    callback=handle_message
)
while True:
    sleep(1)
```
