### ISSUE TITLE
pybit.exceptions.FailedRequestError: Http status code is not 200. (ErrCode: 404)

### ISSUE THREAD

**Issue by Mihlusha** [bybit-exchange/pybit#173]
Hello everyone, tell me why the wallet-balance request does not work?

pybit.exceptions.FailedRequestError: Http status code is not 200. (ErrCode: 404) (ErrTime: 20:26:15).
Request → GET https://api.bybit.com/v5/account/wallet-balance: accountType=UNIFIED.

**Comment by Mihlusha** [comment]
client =  HTTP(

        testnet = False,
        api_key=api_key,
        api_secret=secret_key
    )
    

    print(client.get_wallet_balance(accountType="UNIFIED"))

**Comment by Kamsby** [comment]
If your account is UTA, then use it as UNIFIED, otherwise use it as CONTRACT.

Refer the document - https://bybit-exchange.github.io/docs/v5/account/wallet-balance
