### ISSUE TITLE
pybit.exceptions.FailedRequestError: Http status code is not 200. (ErrCode: 429)

### ISSUE THREAD

**Issue by Pleidak** [bybit-exchange/pybit#182]
My code works fine with version 2.4.1 but it has occurred the below error in recent days, what is the cause, thank you!

> pybit.exceptions.FailedRequestError: Http status code is not 200. (ErrCode: 429)
> Request → GET https://api.bybit.com/public/linear/kline

```
from pybit import usdt_perpetual
session_unauth = usdt_perpetual.HTTP(endpoint="https://api.bybit.com")
*** another code
```

**Comment by dextertd** [comment]
Bybit's V1/V2 APIs have been deprecated. You can upgrade with the help of our API documentation. Please visit our API documentation to assist your migration.
https://bybit-exchange.github.io/docs/

Pybit from =>5.0.0 uses Bybit's V5 API, which is to be supported in the years to come.

For more information:
https://announcements.bybit.com/en/article/bybit-openapi-services-transition-from-legacy-version-to-new-v5-api-blt25b43a5738c00765/?category=product_updates
