### ISSUE TITLE
Finding the earliest kline candle

### ISSUE THREAD

**Issue by einarjohnson** [bybit-exchange/pybit#186]
Hello Pybit folks,
I am working on a project where I store all the Kline data from Bybit in a persistance layer. We use the https://bybit-exchange.github.io/docs/v5/market/kline API to fetch this data.
If there a way for me to figure out what the earliest candle is for a particular ticker so I can start fetching from that date up until the `datetime.now()` ? Since the list returned is sorted in reverse by `startTime` i'm finding it a bit tricky to build a pipeline that fetches the whole history. 

PS: I am fetching the data asynchronously so knowing the earliest candle date upfront would be ideal so I can know which period chunks I should query for.

**Comment by Kamsby** [comment]
There is no endpoint provides the earliest candle. I can suggest you to try with interval as 'M' (month), then pick the last record for your earliest candle reference.

https://api.bybit.com/v5/market/kline?cateory=linear&symbol=BTCUSDT&interval=M&limit=1000

**Comment by einarjohnson** [comment]
that's a good idea @Kamsby , thank you kindly for the input.

**Comment by CompanyXAI** [comment]
You can get the earliest candle in a single request by using a very small start value:

GET /v5/market/kline?category=linear&symbol=BTCUSDT&interval=1&start=9999&limit=1
With start=9999 (ms) and limit=1, the API returns the earliest available 1m candle for that symbol. No need to use monthly intervals or iterate backwards.

Example (BTCUSDT linear): the response gives you the first candle (e.g. 2020-03-25 for BTC). You can then fetch from that timestamp up to now in chunks.
