### ISSUE TITLE
Demo API is not working

### ISSUE THREAD

**Issue by BohdanKharchenko1** [bybit-exchange/pybit#203]
I'm not being able to connect to demo account via demo key. I get invalid key error.

**Comment by dextertd** [comment]
5.7.0 adds support, it will be released in a few hours

**Comment by Nazehs** [comment]
Was this ever released? i keep getting the same error with the demo account keys

`pybit.exceptions.InvalidRequestError: API key is invalid. (ErrCode: 10003) (ErrTime: 21:38:48).
Request → POST https://api-testnet.bybit.com/v5/order/create: {"category": "linear", "symbol": "BTC/USDT", "side": "Buy", "quantity": 0.01, "orderType": "Market"}`

**Comment by dextertd** [comment]
@Nazehs It was. You need to tell pybit that you are using demo trading keys, as they look the same as normal keys. Make sure you're on 5.8.0 and pass `demo=True` to the HTTP session object.

**Comment by pra-dan** [comment]
This works
``` 
from pybit.unified_trading import HTTP

session = HTTP(
    api_key=API_KEY,
    api_secret=API_SECRET,
    demo=True
)

print(session.place_order(
    category="linear",
    symbol="BTCUSDT",
    side="Buy",
    orderType="Market",
    qty=0.001,
))
```

**Comment by vojtajez** [comment]
> @dextertd  Thanks bro you saved me my nerves. Why it isnt on the docs though?

**Comment by devenyiat** [comment]
Hey!
I'm having the exact same issue, but with websockets.
a) If I'm not using the demo=True parameter I get the Api key invalid error, which is kinda expected. Though it is only true for the trading websocket api, all others (e.g. position) work just fine.
b) If I'm using the demo=True parameter, I get 404 on connection, seems like stream-demo.bybit.com simply does not exist
I'm using version 5.11

**Comment by kolya5544** [comment]
> Hey! I'm having the exact same issue, but with websockets. a) If I'm not using the demo=True parameter I get the Api key invalid error, which is kinda expected. Though it is only true for the trading websocket api, all others (e.g. position) work just fine. b) If I'm using the demo=True parameter, I get 404 on connection, seems like stream-demo.bybit.com simply does not exist I'm using version 5.11

WebSocket Trade is not supported on Demo.

**Comment by devenyiat** [comment]
thanks! is this on the roadmap to support it?
