### ISSUE TITLE
I want to pass the orderLinkId to the TPSL order that comes with the limit order.

### ISSUE THREAD

**Issue by ayoub-abdessadak** [bybit-exchange/pybit#213]
When placing a limit order for spot with a TPSL, the TPSL order does not contain information referring to the limit order. The only way to link a limit order and the tpsl order is by checking the values, which can be the same for different limit orders with a TPSL target.

**Comment by dextertd** [comment]
This is impossible. TP/SL/TS are system-managed orders and you can't give them your own `orderLinkId`. You could create a normal order with `place_order()` and manually operate on it so that it acts as TP/SL/TS.
