### ISSUE TITLE
place or cancel orders through websockets?

### ISSUE THREAD

**Issue by vladanyes** [bybit-exchange/pybit#215]
Hey there, does this sdk support [new feature](https://announcements.bybit.com/article/introducing-new-api-feature-websocket-order-placement-blt9d3dc36eff27f1c1/) for placing/canceling orders via websockets?

**Comment by dextertd** [comment]
Not yet

**Comment by vladanyes** [comment]
Looking forward to this 🤞🏼

**Comment by Loremaster** [comment]
@dextertd do you have any ETA on that?
