### ISSUE TITLE
Modernize

### ISSUE THREAD

**Issue by johnslavik** [bybit-exchange/pybit#220]
Hello hello, it's time for some PRs to land
- [ ] Reduce bad code smells
- [ ] Fix some super-weird bugs
- [ ] Add good support for asyncio
- [ ] Add actually useful, correct typing
- [ ] Improve internal thread management (it's a mess)

I would really like to rely on pybit in production, so expect some improvements from me soon :)

**Comment by johnslavik** [comment]
Actually, I've ended up with a simplistic async loop cooked with `websockets`.
I'll close this and maybe rewrite the entire client lib if I have time.

**Comment by Chenger1** [comment]
Created PR with asyncio support: https://github.com/bybit-exchange/pybit/pull/236
