### ISSUE TITLE
v5_account.py get_transaction_log doesn't support a CLASSIC account but the bybit api does

### ISSUE THREAD

**Issue by pjrdata** [bybit-exchange/pybit#225]
get_transaction_log does not work for a classic account.
It assumes a unified account and calls the bybit get_transaction_log function
but for a classic account it seems it should use GET /v5/account/contract-transaction-log as per the doco it refers to here
https://bybit-exchange.github.io/docs/v5/account/contract-transaction-log

**Comment by pjrdata** [comment]
based on the existing get_transaction_log function, I've created a new get_contract_transaction_log function to match contract_transaction_log in the bybit api.
It required updates to these modules
_v5_account.py
acccount.py
Testing has been nicely successful. I've downloaded my entire history for several subaccounts.
Once I remember how to do a pull request I will send it through. Probably tomorrow

**Comment by pjrdata** [comment]
I created the pull request 4 days ago. Hopefully someone has a look at it.

**Comment by dextertd** [comment]
#227
