### ISSUE TITLE
 Copy Trading does not currently support this type of trading. (ErrCode: 12107)

### ISSUE THREAD

**Issue by sigo-byte** [bybit-exchange/pybit#245]
Hi,
I got this error today.
`response = Copy Trading does not currently support this type of trading. (ErrCode: 12107) (ErrTime: 16:15:06).
Request → POST https://api.bybit.com/v5/order/create: {"category": "linear", "symbol": "BTCUSD", "side": "Sell", "orderType": "Limit", "qty": "0.01", "price": "57100", "takeProfit": "55051.2919933816", "stopLoss": "58465.8053377456", "positionIdx": 1}.`
This API worked normally before, but I encountered an issue today.
I tried many things, but I cannot fix it.
Please help me!

**Comment by Kamsby** [comment]
BTCUD is inverse symbol and not supported for Copy Trading. You should use BTCUSDT

**Comment by sigo-byte** [comment]
I got it, thank you!
