### ISSUE TITLE
ping/pong timed out

### ISSUE THREAD

**Issue by ryu878** [bybit-exchange/pybit#31]
After that error message:

WebSocket USDT Perp encountered error: ping/pong timed out.

it just stop working and no reconnect

**Comment by AnyWayFree** [comment]
I also find this problem, how to fix?

**Comment by fahmieshaq** [comment]
Could there be an issue here? https://github.com/bybit-exchange/pybit/blob/master/pybit/_websocket_stream.py
    def is_connected(self):
        try:
            if self.ws.sock or not self.ws.sock.is_connected: ------> Shouldn't we remove 'not'?
                return True
            else:
                return False
        except AttributeError:
            return False

**Comment by fahmieshaq** [comment]
@XWZYC  @ryu878 

Increase your ping_timeout

ws_linear = usdt_perpetual.WebSocket(
    test=False,
    ping_interval=30,  # the default is 30
    ping_timeout=20,  # the default is 10 ----------> CHANGE THIS
    domain="bybit"  # the default is "bybit"
)

**Comment by dextertd** [comment]
Please update to the latest version (2.2.3) and increase your ping timeout and post further details if you still face the error
