### ISSUE TITLE
How to edit stop loss on open position? ErrCode: 10001

### ISSUE THREAD

**Issue by kamilkuczynski** [bybit-exchange/pybit#46]
Hello

I have a problem because I want to change stop loss on the open position but I get always errors. 

This is my code:
entry_price:  1489

actual_bid_price:  1495.8

```
bybitAPI.session_auth.set_trading_stop(
    symbol=symbol,
    side="Buy",
    quantity= amount,
    tp_sl_mode= "Full",
    stop_loss= 1493
)
```

```
================ set up a new stop loss for LONG POSITION ================
long_position:  {'user_id': 2622388, 'symbol': 'ETHUSDT', 'side': 'Buy', 'size': 0.01, 
'position_value': 14.89, 'entry_price': 1489, 'liq_price': 1000.15, 'bust_price': 992.7, 
'leverage': 3, 'auto_add_margin': 0, 'is_isolated': True, 'position_margin': 4.96333324,
 'occ_closing_fee': 0.0059562, 'realised_pnl': -0.1003701, 'cum_realised_pnl': 458.48459275,
 'free_qty': -0.01, 'tp_sl_mode': 'Partial', 'unrealised_pnl': 0.075, 'deleverage_indicator': 2,
 'risk_id': 11, 'stop_loss': 0, 'take_profit': 0, 'trailing_stop': 0, 'position_idx': 1, 'mode': 'BothSide'}
```

```
Traceback (most recent call last):
  File "D:\Python\Trading Bot\ccxt\ccxt_bot_bybit.py", line 167, in <module>
    bybitAPI.session_auth.set_trading_stop(
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\pybit\usdt_perpetual.py", line 475, in set_trading_stop
    return self._submit_request(
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\pybit\_http_manager.py", line 385, in _submit_request
    raise InvalidRequestError(
pybit.exceptions.InvalidRequestError: Param validation for 'side' failed on the 'linear_side' tag (ErrCode: 10001) (ErrTime: 14:54:12).
Request → POST https://api.bybit.com/private/linear/position/trading-stop: 
{'api_key': '', 'quantity': 0.01, 'recv_window': 5000, 'side': 'buy', 'stop_loss': 1493,
 'symbol': 'ETHUSDT', 'timestamp': 1658415251697, 'tp_sl_mode': 'full', 'sign': 
'97f37cfc10c80ec26e74a4e7a17c1ae118837c95f9c527942b5b063def56936a'}.
```

**Comment by obisin** [comment]
Possibly try not sending an amount first and see if you get the error still. set_trading_stop does not require a quantity unless you specify for a sl or tp but this is only in partial mode and you are in Full mode.

This is a link to the relevant documentation:
https://bybit-exchange.github.io/docs/linear/#t-tradingstop

edit: Also tp_sl_mode is not an argument for set_trading_stop. so try removing that also.

**Comment by kamilkuczynski** [comment]
> Possibly try not sending an amount first and see if you get the error still. set_trading_stop does not require a quantity unless you specify for a sl or tp but this is only in partial mode and you are in Full mode.
> 
> This is a link to the relevant documentation: https://bybit-exchange.github.io/docs/linear/#t-tradingstop
> 
> edit: Also tp_sl_mode is not an argument for set_trading_stop. so try removing that also.

THank you for your response, but it doesn't work.

**Comment by dextertd** [comment]
Please also try sending `position_idx`

**Comment by aekramer** [comment]
> > Possibly try not sending an amount first and see if you get the error still. set_trading_stop does not require a quantity unless you specify for a sl or tp but this is only in partial mode and you are in Full mode.
> > This is a link to the relevant documentation: https://bybit-exchange.github.io/docs/linear/#t-tradingstop
> > edit: Also tp_sl_mode is not an argument for set_trading_stop. so try removing that also.
> 
> THank you for your response, but it doesn't work.

You can't set a new trading stop if there is not enough "position size" left, cancel the current one first then you should be able to set a new one quite easily.

You can do so by cancelling a conditional order using the order ID of the first time you used set_trading_stop, if you dont have this order ID you could simply use the "cancel all conditional orders" for the symbol you are trading. (A little bit riskier if you tend to also manually trade on there or may have multiple conditional orders set of which you only want to cancel 1)
