### ISSUE TITLE
Endpoints are unstable and not working over a prolonged period

### ISSUE THREAD

**Issue by casper-hansen** [bybit-exchange/pybit#48]
Here is a traceback. It might be working for 1 hour, then it just starts timing out. Please fix this?

```
Traceback (most recent call last):
  File ".\main.py", line 39, in <module>
    print(ex)
  File ".\main.py", line 28, in start_trading
    endpoint=config['bybit_endpoint'],
  File "C:\Users\caspe\Documents\GitHub\TradingBot\core\transactions\bybit.py", line 45, in start_from_now
    return self._extract_data(get_data_from, interval=interval)
  File "C:\Users\caspe\Documents\GitHub\TradingBot\core\transactions\bybit.py", line 155, in _extract_data
    out = self.session.query_kline(
  File "C:\Users\caspe\miniconda3\envs\tradingbot\lib\site-packages\pybit\usdt_perpetual.py", line 30, in query_kline
    return self._submit_request(
  File "C:\Users\caspe\miniconda3\envs\tradingbot\lib\site-packages\pybit\_http_manager.py", line 291, in _submit_request
    raise e
  File "C:\Users\caspe\miniconda3\envs\tradingbot\lib\site-packages\pybit\_http_manager.py", line 278, in _submit_request
    s = self.client.send(r, timeout=self.timeout)
  File "C:\Users\caspe\miniconda3\envs\tradingbot\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\caspe\miniconda3\envs\tradingbot\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-testnet.bybit.com', port=443): Read timed out. (read timeout=20)
```

**Comment by casper-hansen** [comment]
I already tried increasing the time out.

**Comment by dextertd** [comment]
This is not a problem related to pybit but a standard network problem. When faced with `ReadTimeout` pybit will retry the request once again. So effectively, if you set the ping timeout to 20 seconds, you have to have 40 seconds of an interrupted network before it errors out. This seems like reasonable behaviour to me as you can just adjust the ping timeout to deal with this. To avoid this problem users typically rent a VPS which will provide a stable network.

Please feel free to disagree and give your reasoning.

**Comment by casper-hansen** [comment]
> This is not a problem related to pybit but a standard network problem. When faced with `ReadTimeout` pybit will retry the request once again. So effectively, if you set the ping timeout to 20 seconds, you have to have 40 seconds of an interrupted network before it errors out. This seems like reasonable behaviour to me as you can just adjust the ping timeout to deal with this. To avoid this problem users typically rent a VPS which will provide a stable network.
> 
> Please feel free to disagree and give your reasoning.

I don't think it's a network problem. I have 100% uptime with cable on the testing machine. I can very clearly access any page on the internet while this error happens too.

**Comment by obisin** [comment]
Errors: (just a collection of the error msgs recieved from bybit)
WebSocket USDT Perp encountered error: ping/pong timed out.
WebSocket USDT Perp (Auth) encountered error: Handshake status 502 Bad Gateway.
WebSocket USDT Perp (Auth) encountered error: [Errno 104] Connection reset by peer.
WebSocket USDT Perp (Auth) encountered error: Connection to remote host was lost..
WebSocket USDT Perp (Auth) encountered error: socket is already closed.

I only way around these was to increase the ping/pong and to use bash scripts to restart the script; also update pybit. This isn't a problem with just bybit, it happens with binance also, but bybit do it more. Also I am using a VPS.  

I also get 'tired connections' with any WSGI server I create and the only way round it is to restart it with a bash script. I also get alot less errors using linux terminal rather than windows. 

If you have any better solutions please do let me know.

**Comment by dextertd** [comment]
Please confirm the pybit version you are using

**Comment by casper-hansen** [comment]
> Errors: (just a collection of the error msgs recieved from bybit) WebSocket USDT Perp encountered error: ping/pong timed out. WebSocket USDT Perp (Auth) encountered error: Handshake status 502 Bad Gateway. WebSocket USDT Perp (Auth) encountered error: [Errno 104] Connection reset by peer. WebSocket USDT Perp (Auth) encountered error: Connection to remote host was lost.. WebSocket USDT Perp (Auth) encountered error: socket is already closed.
> 
> I only way around these was to increase the ping/pong and to use bash scripts to restart the script; also update pybit. This isn't a problem with just bybit, it happens with binance also, but bybit do it more. Also I am using a VPS.
> 
> I also get 'tired connections' with any WSGI server I create and the only way round it is to restart it with a bash script. I also get alot less errors using linux terminal rather than windows.
> 
> If you have any better solutions please do let me know.

I think what you mentioned here is a great start, but also a ton of work based on errors on their server side. Perhaps this is not a problem with PyBit specifically, but rather the ByBit API itself that is not stable enough to handle the traffic.

**Comment by casper-hansen** [comment]
> Please confirm the pybit version you are using

I am currently using the latest version 2.4.0.

**Comment by obisin** [comment]
It is 100% Bybit; Binance do this also. They are closing the connection. There is no real way round I can see, other than what I have suggested.

**Comment by casper-hansen** [comment]
> It is 100% Bybit; Binance do this also. They are closing the connection. There is no real way round I can see, other than what I have suggested.

Ok, gotcha. I just found that they only do this when you ping them a lot. Realistically, I only need to ping them every 5 minutes to get the closing price of the interval. 

Below is the code I now use to fetch the data right on the dot. You can just run a while True loop with an if statement on next_timestamp_ready and you will be able to get the data right on the dot.

```python
def round_unix_date(dt_series, seconds=60, up=False):
    # for example, 900 seconds is 15 minutes and will round down when up=False
    return dt_series // seconds * seconds + seconds * up

def next_timestamp_ready(timestamp, config):
    next_interval_close = round_unix_date(timestamp, 60*config['interval'], up=True)

    while next_interval_close > time.time():
        time.sleep(0.01)

    return True
```

**Comment by obisin** [comment]
Thanks for your reply. 

The problem is maintaining the connection to the websocket stream. I need a constant stream of price data. I am well within any rate limits. Pybit will reconnect but sometimes hang or timeout. It takes 4 seconds max to restart my script compared to 1min+ waiting for Pybit.  If I completely restart my connection I get far less future errors which with ping/pong times can stack up. For some reason restarting like this seems to reset something on their side.

**Comment by dextertd** [comment]
> It is 100% Bybit; Binance do this also. They are closing the connection. There is no real way round I can see, other than what I have suggested.

A point of clarification: Bybit won't close your connection if you are pinging frequently enough (20-30 seconds) but the middle network nodes could.

**Comment by dextertd** [comment]
> Thanks for your reply.
> 
> The problem is maintaining the connection to the websocket stream. I need a constant stream of price data. I am well within any rate limits. Pybit will reconnect but sometimes hang or timeout. It takes 4 seconds max to restart my script compared to 1min+ waiting for Pybit. If I completely restart my connection I get far less future errors which with ping/pong times can stack up. For some reason restarting like this seems to reset something on their side.

This is strange. If you want to discuss this, please open a separate issue, and share relevant logs there.

**Comment by casper-hansen** [comment]
> > Thanks for your reply.
> > The problem is maintaining the connection to the websocket stream. I need a constant stream of price data. I am well within any rate limits. Pybit will reconnect but sometimes hang or timeout. It takes 4 seconds max to restart my script compared to 1min+ waiting for Pybit. If I completely restart my connection I get far less future errors which with ping/pong times can stack up. For some reason restarting like this seems to reset something on their side.
> 
> This is strange. If you want to discuss this, please open a separate issue, and share relevant logs there.

I still think there could be an issue with the Bybit endpoint. Have you looked into why we are being disconnected?

**Comment by dextertd** [comment]
Disconnection is just a fact of life and the only advice I can offer to reduce that is to increase the frequency of your pings and locate in the same region as the bybit websocket servers https://bybit-exchange.github.io/docs/inverse/#t-faq_server_location

This will reduce the number of hops between the client and server, thus reducing the chance of disconnection. Based on our comprehensive testing a connection can last for several days in this scenario. If we start testing from a variety of different server locations, different provides, etc, there are too many unknown variables.
