### ISSUE TITLE
Websocket Stream Disconnects

### ISSUE THREAD

**Issue by obisin** [bybit-exchange/pybit#56]
Errors: (just a collection of the error msgs recieved from bybit)
WebSocket USDT Perp encountered error: ping/pong timed out.
WebSocket USDT Perp (Auth) encountered error: Handshake status 502 Bad Gateway.
WebSocket USDT Perp (Auth) encountered error: [Errno 104] Connection reset by peer.
WebSocket USDT Perp (Auth) encountered error: Connection to remote host was lost..
WebSocket USDT Perp (Auth) encountered error: socket is already closed.

These are the errors I keep getting at random times. I am using a VPS.  

The problem is maintaining the connection to the websocket stream. I need a constant stream of price data. I am well within any rate limits. Pybit will reconnect but sometimes hang or timeout. It takes 4 seconds max to restart my script with a bash script compared to 1min+ waiting for Pybit. If I completely restart my connection I get far less future errors which with ping/pong times can stack up. For some reason restarting like this seems to reset something on their side.

-ping_interval=20, ping_timeout=20
-pybit is up to date

**Comment by dextertd** [comment]
Can you show the full log where it takes 1 minute for pybit to restart a websocket connection? If possible, also enable `trace_logging=true` when creating the websocket object. I'd like to see at what time certain log messages are made.

**Comment by q-55555** [comment]
It seems to be a dupplicate of #62 
Any resolution please ?

**Comment by obisin** [comment]
Hi, we went through some resolutions in:

https://github.com/bybit-exchange/pybit/issues/48

Currently I will not be returning to this project at this time as my bot is stable and I do not have the time to go into it any further. We discussed some resolutions in the issue above. They may help.
