### ISSUE TITLE
Get Leverage

### ISSUE THREAD

**Issue by Liso-cz** [bybit-exchange/pybit#58]
Hello,

is there any way how to retrieve currently set leverage? I've found only _set leverage_,  _max_leverage_ etc in sources here and no success with ByBit API Docs. Thanks

**Comment by dextertd** [comment]
https://bybit-exchange.github.io/docs/futuresV2/inverse/#t-myposition

**Comment by Liso-cz** [comment]
Oh, it returns fake position even though there is no position open. Okay, I wouldn't have expected this. Thank you anyway!
