### ISSUE TITLE
example folder

### ISSUE THREAD

**Issue by qkum** [bybit-exchange/pybit#59]
hello there,

im sad to say that it is super disappointing that the "examples" in the example folder, cant even be called examples.

it is "inspiration" at best.

an example is something that is complete...not barely started.

something you can run and it will work out of the box.

it is nice that the basics of creating the connection have been done already.

but just looking at the ocean of functions...how to use them in a safe/correct manner together...

seems more like a try at making people lose their money than an attempt to help if you ask silly me. (im your text-book customer who needs examples to figure out how to use this repo)

ergo, if a person like me gives it 2 out of 5 stars. then there is something seriously wrong.

no hate, just informing.

- have a nice day :)

https://github.com/bybit-exchange/pybit/tree/master/examples

**Comment by qkum** [comment]
a programmer skilled/experienced enough to be paid to work on this repo.

should be able to code a simple working template in 1 hour or something.

one that with simple functionality like opening/closing long/short orders, set stop-loss etc.

nobody can claim that they did a serious attempt in the "examples" folder.

i should be a paid programmer if that is the quality of work you can get paid for.

im super disappointed.

**Comment by dextertd** [comment]
I agree, I am also very unhappy with the examples and in fact general documentation in this repo. I intend to improve it at the same time as implementing the v3 APIs (so as to save time and not have to unnecessarily rewrite documentation).

In the meantime, official bybit API docs include all pybit code examples: https://bybit-exchange.github.io/docs/futuresV2/inverse/

**Comment by dextertd** [comment]
More examples were added in https://github.com/bybit-exchange/pybit/pull/100

Please reopen this issue if you think there are still problems with the examples.
