### ISSUE TITLE
Can't query active order - session.query_active_order()

### ISSUE THREAD

**Issue by wrone** [bybit-exchange/pybit#61]
Hi!

I'm not able to query all active unfilled orders - session.query_active_order(symbol='BTCUSDT') returns an empty array. 

In the same time, session.get_active_order(symbol='BTCUSDT') works well and returns orders. Also, query works when I specify the order id - session.query_active_order(order_id='...', symbol='BTCUSDT')

Am I doing something wrong?

Pybit version: 2.4.0

**Comment by dextertd** [comment]
Stale
