### ISSUE TITLE
Websocket usdt_perpetual stream disconnects and can't reconnect

### ISSUE THREAD

**Issue by Xonitrex** [bybit-exchange/pybit#62]
Hello,

I'm using the usdt_perpetual module to stream Bybit klines.
It works fine for a few hours, but then disconnects.
I enabled `trace_logging=True`, and it doesn't seem to be able to reconnect. Here are the logs :

```
++Rcv raw: b'\x81~\x01\x1b{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850641934}],"timestamp_e6":1662243850641934}'
++Rcv decoded: fin=1 opcode=1 data=b'{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850641934}],"timestamp_e6":1662243850641934}'
++Rcv raw: b'\x81~\x01\x1b{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850644262}],"timestamp_e6":1662243850644262}'
++Rcv decoded: fin=1 opcode=1 data=b'{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850644262}],"timestamp_e6":1662243850644262}'
++Sent raw: b'\x89\x80\xad\x07\x9c2'
++Sent decoded: fin=1 opcode=9 data=b''
WebSocket USDT Perp encountered error: ping/pong timed out.
++Sent raw: b'\x88\x82\xec\xf1\x0f\x85\xef\x19'
++Sent decoded: fin=1 opcode=8 data=b'\x03\xe8'
++Sent raw: b'\x81\xb1\xf2\xc9\x9e\xfa\x89\xeb\xf1\x8a\xd0\xf3\xbe\xd8\x81\xbc\xfc\x89\x91\xbb\xf7\x98\x97\xeb\xb2\xda\xd0\xa8\xec\x9d\x81\xeb\xa4\xda\xa9\xeb\xfd\x9b\x9c\xad\xf2\x9f\xdc\xfc\xb0\xbb\xaa\x9a\xcb\xa9\xb6\x9d\xbc\xa7\x8f'
++Sent decoded: fin=1 opcode=1 data=b'{"op": "subscribe", "args": ["candle.5.AXSUSDT"]}'
error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x00000222BF23CC10>: socket is already closed.
WebSocket USDT Perp encountered error: socket is already closed..
--- request header ---
GET /realtime_public HTTP/1.1
Upgrade: websocket
Host: stream-testnet.bybit.com
Origin: https://stream-testnet.bybit.com
Sec-WebSocket-Key: HF5PXGToDNRnc7JCO3ZDUQ==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
websocket disconnected (retrying in 5 seconds) [7 frames in stack]
HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Accept: jVFinKapUVFnjs3B0R5fx5dZoF4=
Expires: Sat, 03 Sep 2022 22:24:55 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 03 Sep 2022 22:24:55 GMT
Upgrade: websocket
Connection: Upgrade
-----------------------
websocket connected
websocket disconnected (retrying in 5 seconds) [7 frames in stack]
--- request header ---
GET /realtime_public HTTP/1.1
Upgrade: websocket
Host: stream-testnet.bybit.com
Origin: https://stream-testnet.bybit.com
Sec-WebSocket-Key: ZMMWFVzHAzUmatblWoXGKw==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
--- request header ---
GET /realtime_public HTTP/1.1
Upgrade: websocket
Host: stream-testnet.bybit.com
Origin: https://stream-testnet.bybit.com
Sec-WebSocket-Key: GIlYLnCLUGZCaI5hROrnPw==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Accept: 2P12LiCY939ONnncphWCe5Bm4Ug=
Expires: Sat, 03 Sep 2022 22:25:00 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 03 Sep 2022 22:25:00 GMT
Upgrade: websocket
Connection: Upgrade
-----------------------
websocket connected
HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Accept: MMXg+w5KwECRxBzcWxYP+n66txY=
Expires: Sat, 03 Sep 2022 22:25:01 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 03 Sep 2022 22:25:01 GMT
Upgrade: websocket
Connection: Upgrade
-----------------------
websocket connected
++Sent raw: b'\x89\x80\x9f\x89H\x84'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\xe0\xe6\x15\x9f'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\x91\x8f\xf3\xfc'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\x8e\xb5\xf3\x91'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80~\xccC`'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\xd4A\xa3\xc3'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\xa7|\nX'
++Sent decoded: fin=1 opcode=9 data=b''
```

In the first lines, the stream still worked. Then it seems to disconnect, and I haven't received any new values from the stream since. At the end, the last lines ("Sent raw" and "Sent decoded") repeat indefinitely.

I am able to detect a lack of new values, indicating a stream disconnection. I tried some methods to relaunch the stream when I detect this disconnection, but they didn't work.

Thanks for your help !

**Comment by q-55555** [comment]
Same error on my side. Any resolution so far ?

**Comment by q-55555** [comment]
In _websocket_stream => _on_error(self, error), why we don't try to reset and reconnect the websocket if self.attempting_connection is True ? Could we keep only "if self.handle_error" to reset and reconnect ? In the bug, we don't try to reconnect because self.attempting_connection is True.

    def _on_error(self, error):
        """
        Exit on errors and raise exception, or attempt reconnect.
        """

        if not self.exited:
            logger.error(f"WebSocket {self.ws_name} encountered error: {error}.")
            self.exit()

        # Reconnect.
        # Replace with "if self.handle_error:" ?
        if self.handle_error and not self.attempting_connection:
            self._reset()
            self._connect(self.endpoint)

===============================

Another option (maybe better):
In _websocket_stream => def _connect(self, url):

I would move  "self.attempting_connection = False" just after the while loop (while (infinitely_reconnect or retries > 0) and not self.is_connected():). The error might appear when we are calling resubscribe_to_topics. With the current code, self.attempting_connection is True when calling resubscribe_to_topics => if we get an error during this call, we will not reconnect (See def _on_error(self, error):)

**Comment by dextertd** [comment]
I'm not sure how to reproduce this problem.

`attempting_connection` exists to prevent the websocket from attempting to reconnect many times simultaneously, which causes a websocket ban.

**Comment by Xonitrex** [comment]
I understand, do you have any idea to avoid this problem ? _(sorry for the close-reopen missclick)_

**Comment by q-55555** [comment]
Maybe the problem appears when the ping_interval and ping_timeout parameters are close together (for example ping_interval=5 and ping_timeout=4).
If the duration between the 2 parameters is big enough, the probability to meet this error diminishes (just a speculation...)

**Comment by TheMagnat** [comment]
Hello, I'm not sure if it's the same issue, I don't have the time for the moment to try with `trace_logging=True ` but after a certain period of time (something like 1 day) the socket don't receive data anymore. I tried to find a way to solve this issue and I found something interesting :
In `_websocket_stream.py `, the method `is_connected ` use a weird if statement :

https://github.com/bybit-exchange/pybit/blob/63a5a34693e8b227c765281e9210ab1e32df379b/pybit/_websocket_stream.py#L84-L91

the `self.ws.sock` object don't have any `is_connected` member. However, it have a `connected` member that look to work the way you want to use it in this if statement.

edit: since it's a `or` I'm not sure if this prevents disconnection detection (I don't know well the web socket package) but for me this if statement should be `if self.ws.sock and self.ws.sock.connected`.

**Comment by q-55555** [comment]
I agree `if self.ws.sock and self.ws.sock.connected` makes more sense.
@dextertd what do you think ?

**Comment by dextertd** [comment]
Hi everyone, thank you for your contributions in this thread so far. After further testing I made some more changes to the WS reconnection logic. You can see the changes in this commit https://github.com/bybit-exchange/pybit/commit/83415cf9b3850b6a9350d73842efad53465abc41

Essentially, `is_connected()` now just checks `self.ws.sock.connected`. This should work better.

I also added a while loop which should improve the whole reconnection process by making sure we are done with the present connection attempt before trying again with a new connection.

Based on my testing this should work well. But please try it out with this pre-release and let me know how it works for you.

```
pip install pybit==2.4.1rc0
```

**Comment by Liso-cz** [comment]
Hi guys,
I had similar issue yesterday and this thread helped me a lot.

Here is my solution in another thread: https://github.com/bybit-exchange/pybit/issues/75#issuecomment-1287280351

Briefly, I've tried also the new 2.4.1rc0 version, but without any change. In the end, it was firewall issue with ping/pong on IPv6.

**Comment by q-55555** [comment]
@dextertd 2.4.1rc0 works well so far. Maybe we can merge 83415cf with the master branch.
