### ISSUE TITLE
Occasionally face "error sign!" when calling USDC methods

### ISSUE THREAD

**Issue by Madanraj-Delta** [bybit-exchange/pybit#63]
Getting issue while trying to get wallet balances or positions.

`

from pybit import usdc_options, usdc_perpetual

def connect():
		bybit_client = usdc_options.HTTP(
			endpoint=base_url,
			api_key='XX',
			api_secret='XX',
			recv_window=10000
		)
		return bybit_client

base_url = "https://api.bybit.com"
bybit_client = connect()

balances_response = bybit_client.get_wallet_balance()
print(balances_response)
`

Not always there is an issue, but fails frequently.
My time is sync with UTC time only.

This is the error message,

 **raise InvalidRequestError(
pybit.exceptions.InvalidRequestError: Error sign! (ErrCode: 10004) (ErrTime: 07:45:20).**

@lucilae @Kamsby @dextertd @songhaitao @sangechen

**Comment by dextertd** [comment]
#64 should fix it. Please give it a go.

**Comment by Madanraj-Delta** [comment]
Sure, thanks. When does master gets deployed to check the same and also im using 2.2.1. Does it reflect there? @dextertd

**Comment by dextertd** [comment]
I'll try to release it later today and let you know the new version number.

**Comment by dextertd** [comment]
@Madanraj-Delta Please try the pre-release:

```
pip install pybit==2.4.0rc0
```

**Comment by Madanraj-Delta** [comment]
```
raise InvalidHeader("Value for header {%s: %s} must be of type str or "
requests.exceptions.InvalidHeader: Value for header {X-BAPI-TIMESTAMP: 1663300561442} must be of type str or bytes, not <class 'int'>

```
Getting this error in the pre-release @dextertd

**Comment by dextertd** [comment]
Sorry for the delay in my response.

I made a mistake testing this, which has been just been fixed, and you can try it `pybit==2.4.0rc1`

**Comment by dextertd** [comment]
Based on my testing the pre-release works so I'm going to close this issue.

**Comment by Madanraj-Delta** [comment]
@dextertd Getting the same issue in bybit spot. 

> (Timestamp for this request is outside of the recvwindow. (ErrCode: -1021) (ErrTime: 00:30:28).
> Request → GET https://api.bybit.com/spot/v1/account: {'api_key': 'XX', 'recv_window': 10000, 'timestamp': 1669768215867, 'sign': 'e40f696938703c8b2ee807fa56230d1fbd65eccafef94fb288572933379f56b9'}
> )

 Could you please help on this.

**Comment by dextertd** [comment]
@Madanraj-Delta  Please provide more information. What version of pybit are you using? Does this happen constantly or occasionally?

Edit: solved elsewhere.
