### ISSUE TITLE
Connection reset by peer - randomly occurring

### ISSUE THREAD

**Issue by aekramer** [bybit-exchange/pybit#67]
I seem to be "randomly" getting the following error:
`requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

I am not sure what the cause for this is, after the bot has just started there does not seem to be any issue at all, it's after it has been running for a little while (it seems like). This error occurs while trying to poll wallet data as well as trying to place orders (so kind of a big deal..)

Is it intended to create a new HTTP session each time you want to perform some actions?
For example every time I try to create an order and add multiple trading stops, I recreate a new http session?

EDIT: The weird part is that it seems to go back to working a little bit after the failed attempt (but only temporarily)
It's as if the connection goes into some kind of sleep state then gets nudged to wake up and slowly restores itself (temporarily)
This does NOT happen quickly though, sometimes I can ask to poll the wallet info 3-5 times over the span of a couple of minutes before it finally works again.

**Comment by dextertd** [comment]
Related #75
