### ISSUE TITLE
position_idx is not present in close_position function.

### ISSUE THREAD

**Issue by bsjaramillo** [bybit-exchange/pybit#68]
I've been trying to close a position but i had the error "position_idx not match with my position mode", so to fix it, i had to add position_idx field to close_position function, but i cant do this inside a docker container.
![image](https://user-images.githubusercontent.com/33032851/191789490-3b31425b-b1d7-4f6b-b4bd-4ee8591e2f5c.png)

**Comment by dextertd** [comment]
https://github.com/bybit-exchange/pybit/pull/161
