### ISSUE TITLE
Websocket usdt_perpetual query_kline returns 0 results in docker

### ISSUE THREAD

**Issue by notiqq** [bybit-exchange/pybit#73]
Hi,

I was trying to use usdt_perpetual query_kline method from latest stable version + 2.4.1rc0 version. For both versions it works well locally, but once I'm wrapping up application inside docker it stops to return results. 

`
self.session = usdt_perpetual.HTTP(
            endpoint="https://api-testnet.bybit.com",
            api_key=BYBIT_API_KEY,
            api_secret=BYBIT_API_SECRET
        )
def __get_timestamp_now(self):
        date_time = time.mktime(datetime.utcnow().timetuple())
        return date_time

klines = self.session.query_kline(symbol=ticker,interval=interval, from_time=self.__get_timestamp_now())

`

requirements.txt

`
pandas==1.4.2
pymongo==4.1.1
dnspython==2.2.1
requests>=2.22.0
websocket-client>=0.57.0
pybit==2.4.1rc0
`

Dockerfile
`
FROM python:3.8

COPY ./app/ ./

RUN pip install -r requirements.txt

CMD ["python", "main.py"]

`

**Comment by dextertd** [comment]
Stale
