### ISSUE TITLE
Websocket Spot topics don't resubscribe after connection errors

### ISSUE THREAD

**Issue by damianope** [bybit-exchange/pybit#76]
When using websocket in Spot, the list `self.subscriptions` is always empty. So in case of a connection error, when the connection is reopen, previous topics aren't resubscribed.

I simply fixed it adding `self.subscriptions.append(json.dumps(topic))` at the end of the `subscribe` method inside `_SpotWebSocketManager` class.

**Comment by dextertd** [comment]
Fixed in this pre-release pip install pybit==2.4.2rc0
