### ISSUE TITLE
query symbol info by sybmol

### ISSUE THREAD

**Issue by quantfreedom** [bybit-exchange/pybit#78]
i want to know specific info like the min trade quantity of a symbol but i have to do a for loop to get to the symbol then i can look for the min quantity 

do you guys plan on allowing us to send the symbol as a parameter ... doesn't seem like it should be necessary to for loop to get the info of a symbol

min_trading_qty = 0
for i in pybit_bybit_test_ex.query_symbol()['result']:
	if i['name'] == tradingPair_pybit:
		min_trading_qty = i['lot_size_filter']['min_trading_qty']

i should just be able to do 
pybit_bybit_test_ex.query_symbol(tradingPair_pybit)['lot_size_filter']['min_trading_qty']

**Comment by dextertd** [comment]
`symbol` param is supported in v5's equivalent endpoint https://bybit-exchange.github.io/docs/v5/market/instrument
