### ISSUE TITLE
Impossible to open trailing stop on MergedSingle

### ISSUE THREAD

**Issue by SamRosto** [bybit-exchange/pybit#81]
It does not make any sense that it is impossible to open trailing stop for MergedSingle position mode through API (pybit). In the meantime it is possible to set up trailing stop through the bybit app in a MergedSingle position mode. Could you please fix it
Thx

**Comment by dextertd** [comment]
What error do you face? This should work just fine. Closing as potentially stale, please feel free to reopen.
