### ISSUE TITLE
i can't install the package 

### ISSUE THREAD

**Issue by FedeOn360hz** [bybit-exchange/pybit#82]
Hello, when i trie to install pybit with pycharm i get this error, pls someone help me!!
![error pybit](https://user-images.githubusercontent.com/87227203/205986975-eb8e26ba-b456-4bcc-b777-a54497013df5.png)

**Comment by dextertd** [comment]
I think that this problem has to be brought up with Anaconda, if it has not been solved already. (Please correct me if I'm wrong.)
