### ISSUE TITLE
Is there a way to interact with bots?

### ISSUE THREAD

**Issue by veganish** [bybit-exchange/pybit#89]
Hi,

I would like to be able to interact with grid bots.  Ideally, monitor the specific bot and being able to terminate it.  Is there a way to do this in this API? 

Thanks for any help!

**Comment by skwskwskwskw** [comment]
Hi can I have an answer for this as well? It seems like no such feature available for pybit. 

Thanks!

**Comment by dextertd** [comment]
If you're referring to https://www.bybit.com/en/tradingbot/

The answer is no, there is no API support for this.

**Comment by skwskwskwskw** [comment]
okie noted  - wish this feature could be added...

**Comment by skwskwskwskw** [comment]
> If you're referring to https://www.bybit.com/en/tradingbot/
> 
> The answer is no, there is no API support for this.

Just wondering, are there any API connected to AuroraAI?
