### ISSUE TITLE
Question: access point to Order History?

### ISSUE THREAD

**Issue by gilbh** [bybit-exchange/pybit#96]
I was unable to find in pybit or using ccxt a way to get my Order History and Trade History (in my case, for derivatives in USDT), like you can find here:

https://www.bybit.com/user/assets/order/all-orders/usdt
https://www.bybit.com/user/assets/order/trade-history/usdt

![image](https://user-images.githubusercontent.com/39532610/224484616-060159b4-6ac9-4b97-a0b1-09eb145f9696.png)

![image](https://user-images.githubusercontent.com/39532610/224485528-884f8ba1-4e09-41f9-81a4-3a2d01d1b925.png)

Is there such a thing?

Thanks!

**Comment by atilagf1** [comment]
CCXT is horrible.
You don't have a method for historical order, only for open order. If you truly need your order history, you can make your own scrapping code. Second give a look for the Position endpoint methods. You do have a method for trades history: user_trade_records() .

**Comment by atilagf1** [comment]
CCXT is horrible.
You do have a method for order history: user_trade_records() and trades history: user_trade_records() .

**Comment by atilagf1** [comment]
You don't have a method to get order history, but you could do that with web scrapping. You can use user_trade_records() to get trade history.

**Comment by gilbh** [comment]
Thanks!

I ended up opting for `usdt_perpetual.closed_profit_and_loss`, which fits best my needs:
```
session = usdt_perpetual.HTTP(
    endpoint='https://api.bybit.com',
    api_key=API_DICT['API_KEY'],
    api_secret=API_DICT['API_SECRET']
)
res = session.closed_profit_and_loss(category='linear')
```

-- but it seems the symbol is required (I am guessing this is b/c of having Unified Account and not Normal??):
```
InvalidRequestError: Params error: symbol invalid  (ErrCode: 10001) (ErrTime: 13:52:55).
Request → GET https://api.bybit.com/private/linear/trade/closed-pnl/list: {'api_key': '...', 'category': 'linear', 'recv_
window': 5000, 'timestamp': 1678629175006, 'sign': '...'}.
```

I tested with explicitly sending a symbol:
```
res = session.closed_profit_and_loss(category='linear', symbol='BTCUSDT')
```

-- and it works.

This is discouraging since I don't want to iterate over each coin ... any thoughts?

Love your code. Thanks for the help!

**Comment by atilagf1** [comment]
Symbol is required as parameter.

**Comment by atilagf1** [comment]
You can see it here: https://bybit-exchange.github.io/docs-legacy/futuresV2/linear/#t-closedprofitandloss

**Comment by gilbh** [comment]
This is ridiculous: bybit can't think of someone interested in *all* available symbols?? 

This seems to leave two bad options: either to scrape (but how to automate the login, which is very often with bybit?) or to iterate for every coin (200 or so calls??) ...

**Comment by atilagf1** [comment]
You can make a list with all coin pair use another endpoint, then use it to iterate and call for each symbol.

**Comment by gilbh** [comment]
... and then aggregate to one df according to trade dates ... some work ahead ... but better than scraping i guess.

Thanks!!

**Comment by dextertd** [comment]
It's very costly to the API to disable the `symbol` parameter. If you wanted to get this data the best thing to do would be to ask support@bybit.com and use the CSVs provided to maintain your own local database. The API is not really intended to be used to copy all a user's data, it's not very efficient to use an API for this.
